"""Reindex the vault's LanceDB atom index from on-disk markdown.

Phase 1 embeds every atom on write. Three things can leave the index out
of sync with the vault, all of which `reindex` fixes:

  1. The LanceDB directory got wiped or moved.
  2. An atom file was added manually (or generated by a not-yet-built
     external tool like the Phase 6 pattern distiller).
  3. The embedding strategy changed (e.g. USE_TYPE_PREFIX flipped) and
     existing vectors no longer reflect the current input shape.

Strategy: walk `03_Atoms/*.md`, parse each frontmatter + body, hydrate
back into Atom, then `upsert` into the index. With `--force`, every atom
re-embeds; otherwise we skip atoms already present in `list_atom_ids()`.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date as _date, datetime as _datetime
from pathlib import Path

import frontmatter

from consultant_brain.embedder import LanceVaultIndex
from consultant_brain.schemas import (
    Atom,
    AtomStatus,
    AtomType,
    CallType,
)
from consultant_brain.vault import VaultLayout


@dataclass(frozen=True, slots=True)
class ReindexSummary:
    """Outcome of one reindex run. Printed by the CLI."""

    scanned: int
    embedded: int
    skipped: int
    failed: list[Path]

    def summary_line(self) -> str:
        failed_part = f", {len(self.failed)} failed" if self.failed else ""
        return (
            f"Reindex: scanned {self.scanned}, embedded {self.embedded}, "
            f"skipped {self.skipped} (already in index){failed_part}"
        )


def run_reindex(*, vault_root: Path, force: bool = False) -> ReindexSummary:
    """Walk the atoms dir, embed anything missing from the index."""
    layout = VaultLayout.for_root(vault_root)
    if not layout.atoms_dir.exists():
        return ReindexSummary(scanned=0, embedded=0, skipped=0, failed=[])

    index = LanceVaultIndex(layout)
    existing_ids = set() if force else index.list_atom_ids()

    scanned = 0
    embedded = 0
    skipped = 0
    failed: list[Path] = []

    for atom_path in sorted(layout.atoms_dir.glob("*.md")):
        scanned += 1
        try:
            atom = _atom_from_markdown(atom_path)
        except Exception:
            failed.append(atom_path)
            continue

        if atom.id in existing_ids and not force:
            skipped += 1
            continue

        try:
            index.upsert(atom)
            embedded += 1
        except Exception:
            failed.append(atom_path)

    return ReindexSummary(scanned=scanned, embedded=embedded, skipped=skipped, failed=failed)


def _atom_from_markdown(path: Path) -> Atom:
    """Parse one atom markdown file back into an Atom model.

    The vault writer renders client + call as wikilinks (`[[Reece]]`,
    `[[2026-05-12_reece_consultingCall]]`); we strip the brackets on the
    read path so the Atom validator sees the underlying values.
    """
    with path.open("r", encoding="utf-8") as f:
        post = frontmatter.load(f)
    meta = dict(post.metadata)

    body = (post.content or "").strip()
    return Atom(
        id=meta["id"],
        type=AtomType(meta["type"]),
        client=_strip_wikilink(meta.get("client")),
        call=_strip_wikilink(meta["call"]),
        call_type=CallType(meta["call_type"]),
        tags=list(meta.get("tags") or []),
        confidence=float(meta.get("confidence", 0.5)),
        evidence_count=int(meta.get("evidence_count", 1)),
        last_seen=_coerce_date(meta.get("last_seen")),
        created_at=_coerce_datetime(meta.get("created_at")),
        status=AtomStatus(meta.get("status", "active")),
        embedding_id=meta.get("embedding_id", meta["id"]),
        body=body,
    )


def _strip_wikilink(value) -> str | None:
    """Turn `[[Reece]]` back into `Reece`. Tolerates plain strings or None."""
    if value is None:
        return None
    s = str(value).strip()
    if s.startswith("[[") and s.endswith("]]"):
        return s[2:-2]
    return s or None


def _coerce_date(value) -> _date:
    if isinstance(value, _date) and not isinstance(value, _datetime):
        return value
    return _date.fromisoformat(str(value))


def _coerce_datetime(value) -> _datetime:
    if isinstance(value, _datetime):
        return value
    s = str(value)
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    return _datetime.fromisoformat(s)
